### ISSUE TITLE
无法新建文章提示500错误

### ISSUE THREAD

**Issue by SylarMa** [gethexon/hexon#17]
系统ubuntu 22.04

  <-- POST [secure]/hexo/create
[auth-storage-service][2022-08-25 10:21:42.766] get secret
[exec-service][2022-08-25 10:21:42.770] run hexo new aaa
INFO  Start processing
  xxx POST [secure]/hexo/create 500 837ms -
[app][2022-08-25 10:21:43.602] TypeError: Cannot read properties of undefined (reading 'trim')
    at HexoService.create (/home/blog/hexon/server/dist/index.js:4264:64)
    at async /home/blog/hexon/server/dist/index.js:4371:14
    at async serve (/home/blog/hexon/server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async logger (/home/blog/hexon/server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
    at async /home/blog/hexon/server/dist/index.js:2899:7
    at async compressMiddleware (/home/blog/hexon/server/node_modules/.pnpm/koa-compress@5.1.0/node_modules/koa-compress/lib/index.js:52:5)
    at async bodyParser (/home/blog/hexon/server/node_modules/.pnpm/koa-bodyparser@4.3.0/node_modules/koa-bodyparser/index.js:95:5)
    at async /home/blog/hexon/server/dist/index.js:4638:5

**Comment by YuJianghao** [comment]
你的 hexon, hexo 版本是什么？我应该怎么复现？
